#!/bin/bash
. parameters.conf
. bck_functions.sh
check_param
if [ ! -e $backup_root"monthly"/$Month ]
  then
    mkdir -p $backup_root"monthly"/$Month 2>/dev/null
    check_folder_creation
  fi
  do_backup $Month Monthly
  exit $?;
fi
