#!/bin/bash
. parameters.conf
. bck_functions.sh

week_backup(){
  if [ ! -e $backup_root"weekly"/"$1" ]
    then
      mkdir -p $backup_root"weekly"/"$1" 2>/dev/null
      check_folder_creation
  fi
  do_backup $1 weekly
  exit $?;
}

WEEK=" "

if [ $DAY_week = "sat" ] || [ $DAY_week = "sab" ] && [ $DAY_num -le 7 ]
  then
    WEEK="week1"
elif [ $DAY_week = "sat" ] || [ $DAY_week = "sab" ] && [ $DAY_num -gt 7 ] && [ $DAY_num -le 14 ]
  then
    WEEK="week2"
elif [ $DAY_week = "sat" ] || [ $DAY_week = "sab" ] && [ $DAY_num -gt 14 ] && [ $DAY_num -le 21 ]
  then
    WEEK="week3"
elif [ $DAY_week = "sat" ] || [ $DAY_week = "sab" ] && [ $DAY_num -gt 21 ] && [ $DAY_num -le 28 ]
  then
    WEEK="week4"
fi

check_param
week_backup $WEEK
